name: Release
on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install SourceMod
        uses: KatsuteTF/Workflows/actions/setup-sourcepawn@main

      - name: Install TF2Attributes
        uses: KatsuteTF/Workflows/actions/curl@main
        with:
          url: https://raw.githubusercontent.com/FlaminSarge/tf2attributes/master/scripting/include/tf2attributes.inc
          file: tf2attributes.inc

      - name: Install RRM
        uses: KatsuteTF/Workflows/actions/curl@main
        with:
          url: https://raw.githubusercontent.com/KatsuteTF/RRM/main/addons/sourcemod/include/rrm.inc
          file: rrm.inc

      - name: Compile
        run: |-
          for file in *.sp; do
              spcomp -i ./ "$file"
          done

      - name: Package
        run: zip plugins.zip *.smx

      - name: Deploy to GitHub Releases
        uses: AButler/upload-release-assets@v4.0.0
        with:
          files: "plugins.zip"
          repo-token: ${{ secrets.GITHUB_TOKEN }}